### ISSUE TITLE
Where could I find gitlab.baidu.com/hanshinan/godarts ?

### ISSUE THREAD

**Issue by pombredanne** [anknown/ahocorasick#2]
Where could I find gitlab.baidu.com/hanshinan/godarts ?
https://github.com/anknown/ahocorasick/blob/master/ahocorasick.go#L8 ?
I cannot access http://gitlab.baidu.com/hanshinan/godarts

**Comment by anknown** [comment]
sorry, i ever change the git repo, you should use "github.com/anknown/darts" instead. i've already fix this bug, you can also check it in the codes

**Comment by pombredanne** [comment]
Thanks!. I should have closed this a long time ago!
