### ISSUE TITLE
Is it safe for multiple goroutines to call MultiPatternSearch concurrently on the same Machine?

### ISSUE THREAD

**Issue by kmanley** [anknown/ahocorasick#3]
Hi, I just opened an issue because I'm not sure how else to contact you. I really like this lib and am using it, thank you for open sourcing it! 

Just a quick question. Given a Machine that is returned from Build, is it safe for multiple goroutines to call MultiPatternSearch concurrently on that Machine? I think the answer is yes but just want to be sure.

Thanks, Kevin

**Comment by anknown** [comment]
I'am very glad to know you like this code, and the answer is yes :D
