### ISSUE TITLE
feature request: case insensitive matching

### ISSUE THREAD

**Issue by kmanley** [anknown/ahocorasick#5]
Currently matching is always case sensitive. Obviously the machine could be built with lowercase dict, and input text could be lower cased, but it could be more efficient for the case insensitive matching to happen in the matching logic itself, especially in the case where returnImmediately=true

**Comment by anknown** [comment]
I did not support a case insensitive feature in the logic because the code always need to support other languages, such as Chinese and Janpanese, which do not have this problem, so the best way is do just like what you said. :D

**Comment by BarnabasSzabolcs** [comment]
yeah, it leads to a bit of difficulty with German where some words are upper- and lowercase, some are uppercase only and some are lowercase only.
I'll probably add tuple values to the trie.

Your implementation of the algorithm is pretty performant btw, I love it, congrats!
(copilot has recommended you)
