### ISSUE TITLE
You must give appropriate credit to reference projects

### ISSUE THREAD

**Issue by hankcs** [anknown/ahocorasick#7]
Hi anknown, or should I call you 韩诗楠.

Thank you for your effort porting Aho Corasick with DoubleArrayTrie to golang. But please give appropriate credit to other projects you benefited from.

Your [benchmark](https://github.com/anknown/ahocorasick/tree/master/benchmark) is copied from [my project](https://github.com/hankcs/AhoCorasickDoubleArrayTrie/tree/master/src/test/resources). Why didn't you even mention it?

I haven't read your code yet, but as we (including pioneers I mentioned in my projects) are implementing almost the same algorithm. Did you borrow any ideas from them? If you did, you should give credit to them.

In a worldwide community like GitHub, we Chinese should show more respect for copyright. Otherwise we are always the joke.

Thank you!

**Comment by anknown** [comment]
Thank you for reminding, I've already fixed ：）

**Comment by hankcs** [comment]
Thank you for your cooperation.
